# Generated by Django 5.2 on 2025-06-01 07:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_requests', '0002_initial'),
        ('users', '0002_user_id_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(choices=[(1, '1 - גרוע מאוד'), (2, '2 - גרוע'), (3, '3 - בסדר'), (4, '4 - טוב'), (5, '5 - מעולה')])),
                ('comment', models.TextField()),
                ('category', models.CharField(choices=[('website', 'האתר'), ('process', 'תהליך הבקשות'), ('support', 'שירות לקוחות'), ('general', 'כללי')], default='general', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_anonymous', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='users.user')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
