# Generated by Django 5.2 on 2025-06-05 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_requests', '0003_feedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='category',
            field=models.CharField(choices=[('website', 'האתר'), ('process', 'תהליך הבקשות'), ('general', 'כללי')], default='general', max_length=50),
        ),
    ]
